source 'https://rubygems.org'
ruby '2.2.2'
gem 'sinatra'
gem 'twitter'
gem 'sinatra-contrib'
gem 'natto'
gem 'mecab', '0.996'
gem 'aws-sdk'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'sqlite3', '1.3.11'